//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int id { get; set; }
        public string deviceId { get; set; }
        public string cowId { get; set; }
        public string date { get; set; }
        public string timestamp { get; set; }
        public Nullable<int> threshold { get; set; }
        public Nullable<int> value1 { get; set; }
        public Nullable<int> value2 { get; set; }
        public Nullable<int> value3 { get; set; }
        public Nullable<int> value4 { get; set; }
        public Nullable<int> value5 { get; set; }
        public Nullable<int> value6 { get; set; }
        public Nullable<int> value7 { get; set; }
        public Nullable<int> value8 { get; set; }
        public Nullable<int> value9 { get; set; }
        public Nullable<int> value10 { get; set; }
        public Nullable<int> value11 { get; set; }
        public Nullable<int> value12 { get; set; }
        public Nullable<int> value13 { get; set; }
        public Nullable<int> value14 { get; set; }
        public Nullable<int> value15 { get; set; }
        public Nullable<int> value16 { get; set; }
        public Nullable<int> value17 { get; set; }
        public Nullable<int> value18 { get; set; }
        public Nullable<int> value19 { get; set; }
        public Nullable<int> value20 { get; set; }
        public Nullable<int> value21 { get; set; }
        public Nullable<int> value22 { get; set; }
        public Nullable<int> value23 { get; set; }
        public Nullable<int> value24 { get; set; }
    }
}
